# Generated by Django 5.1.7 on 2025-05-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='Q0', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
